spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${app.jwt.issuer-uri}
          jwk-set-uri: ${app.jwt.issuer-uri}/protocol/openid-connect/certs

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      enabled: true
      show-details: "when-authorized"
      roles:
        - "ADMIN"
    info:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

app:
  cors:
    allowed-origins: http://localhost:3000

  jwt:
   keycloak: http://localhost:8443
   realm: app
   issuer-uri: ${app.jwt.keycloak}/realms/${app.jwt.realm}
   resource-client-id: frontend-web

logging:
  level:
    com.example.backend: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # (create, create-drop, validate, update)
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  jwt:
    keycloak: http://keycloak:8443

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html